////
Copyright (c) 2019 Vinnie Falco (vinnie.falco@gmail.com)
Copyright (c) 2025 Dmitry Arkhipov (grisumbras@yandex.ru)

Distributed under the Boost Software License, Version 1.0. (See accompanying
file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

Official repository: https://github.com/boostorg/json
////

= 常见问题

"Isn't simdjson faster?":: 这些库不可相提并论。simdjson 解析器的输出是一个只读结构。换句话说，它不能被修改，创建它的唯一方法是解析一个 JSON 字符串。另一方面，Boost.JSON 允许你修改容纳已解析 JSON 的容器，甚至可以通过容器接口从头构建 JSON 文档。
"为什么使用 <<ref_storage_ptr>> 而不是 {ref_polymorphic_allocator}？":: {ref_polymorphic_allocator} 将内存资源视为所有权的引用。Boost.JSON 使用一个引用计数智能指针容器来简化内存资源的生命周期管理。除了引用计数外，<<ref_storage_ptr>> 还可以作为围绕 {ref_memory_resource} 的非计数引用包装器。

"Why not use a standard {req_Allocator}?:: 使用标准分配器将要求 <<ref_value>> 被声明为一个类模板，这会增加额外的编译负担。通过避免使用模板，库中的大部分函数定义可以从头文件中排除，并放入单独的静态库或动态库中。
require that <<ref_value>> be declared as a class template, which would impose an additional compilation burden. By avoiding the template, most of the function definitions in the library can be excluded from the headers and emitted in a separate static or dynamic library.

"Why use <<ref_storage_ptr>> over {ref_polymorphic_allocator}?:: {ref_polymorphic_allocator} treats the memory resource as a reference with respect to ownership. Boost.JSON uses a reference counted smart pointer container to simplify the lifetime management of memory resources. In addition to being reference counted, <<ref_storage_ptr>> can function as an uncounted reference wrapper around a {ref_memory_resource}.


"Why <<ref_string>> instead of {std_string}?":: 该库提供的字符串使用 <<ref_storage_ptr>>分配器模型，在所有 C++ 版本上具有相同的接口，并具有优化的类布局以保持 JSON 值的大小较小。<<ref_string>> 还实现了一个改进的接口，该接口使用 <<ref_string_view>> 替代了多余的重载。
library uses the <<ref_storage_ptr>> allocator model, has the same interface on all C++ versions, and has an optimized class layout to keep the size of JSON values small. <<ref_string>> also implements an improved interface that replaces extraneous overloads with ones that use <<ref_string_view>>.
